### ISSUE TITLE
在NEXT beta2版本首次安装点击相册没反应

### ISSUE THREAD

**Issue by LXLYHM** [conerjoy/ScanDemo-harmony#1]
在NEXT beta2版本首次安装点击相册没反应，相册权限方法没走进去

**Comment by conerjoy** [comment]
原因：点击相册会调起读取媒体权限，向系统申请权限没有得到任何回调，导致没反应，回调方法也没走
修复方式：查看官网调用相册api，发现不需要媒体权限即可调起相册，遂去掉读取媒体权限申请，直接调起相册

**Comment by conerjoy** [comment]
已修复，修复版本1.0.4
